name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  sast-and-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les outils de sécurité (Étape 1 & 3)
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pip-audit safety

      - name: 01 - Linting avec Flake8
        run: |
          # Arrête le build s'il y a des erreurs de syntaxe graves
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Affiche les warnings sans bloquer
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: 02 - Scan des vulnérabilités des dépendances (pip-audit & safety)
        run: |
          pip-audit -r requirements.txt
          safety check -r requirements.txt


      - name: 03 - Analyse SAST (SonarCloud)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true 

  build-and-dast:
    needs: sast-and-linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: 04 - Build de l'image Docker
        run: |
          docker build -t secops-app:latest .

      - name: Run Docker Container (Préparation pour ZAP)
        run: |
          docker run -d -p 5050:5050 --name secops-flask-app secops-app:latest
          sleep 10 # Attendre que Flask démarre

      - name: 05 - Scan DAST (OWASP ZAP)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5050'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'